dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    secure: ZFITEfGBDmyhD35owkPjlhhxuB4pGTtVIMdnlTDuGjYIGDabMEsbQGjXL6Qsnllg2QRa86b5rC8TflUyFmdBx0JcrPLytQvWQUz+C255uSuahW7xMmkC6BVWsNUZ76HR8gcyouMX7KZ6oXB6tffC8VeUNqvHRcsfjZe9rkR/k/dgp03Y8z4ZcPMZFQGc32aG5OAfob5tYLOQedq7gk6tolVuDgs9dKv38gF7kdqZNhcL8ixGyMsblVYhw3Q+JThTIF4x+BZLUIBFQW6LGNvnnd3PBPg285WujPXSkF7wduA6IAOZkBhVi38osjb9wkVmh7DnydIg1/gDOeig0NoJFmsWRq3u07j9Ur0BcutcnP+T/CJOvQFKiLsQZg1adAylQjjhzZ89C0BJPbyQ4DG50+DvpsCFPfxaXPCp6V0b4gSgZat8d18HeS87FxeLluQpGRmTGFetFv1IaY1cci0uYx2gF9O8+s4LUZxqg/5N5IhyipdrMZTL9P2EU5MxoSAlEAmxBAx45LAcRss9ffxbQ2Sf9Lfoiiy/RWx0E6h6aR11l5vI5c5S6HX/7R9IKEruZSRTWtJS++j5qtLbcrhuI+cYTcuy6VQXQFUPQdZBb9zdjq6bwtEl0QSbtGlkvMZnA/G43TyJtNIBh9I2xLUtsGkrLhxpI762MtAjIin3h84=
